# GitHub Actions workflow to build and test a Go project.
name: "Go"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: "go-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event.action != 'merge_group' }}"

jobs:
  build:
    name: "Build"
    uses: HyperaDev/actions/.github/workflows/go-build.yml@main
    with:
      # go_version: ""
      # go_build_args: ""
      # codecov_enabled: false
      # codecov_files: ""
      # codecov_directory: ""
      # lint_enabled: false
      # vulncheck_enabled: true
      # upload_artifacts: ""
