# GitHub Actions workflow to build a Gradle project.
name: "Gradle"
on:
  push:
    branches: [ "main" ]
    tags-ignore: ["**"]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  build:
    name: "Build"
    uses: HyperaDev/actions/.github/workflows/gradle-build.yml@main
    with:
      # java_version: "21"
      # gradle_extra_args: ""
      # gradle_warning_mode: "fail"
      # codecov_enabled: false
      # codecov_files: ""
      # codecov_directory: ""
      # upload_artifacts: ""
