# GitHub Actions workflow to publish releases.
# Releases are published from the 'releases/<major>' branches.
name: "Gradle"
on:
  push:
    branches: [ "releases/**" ]

concurrency:
  group: "gradle-release-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: "Release"
    uses: HyperaDev/actions/.github/workflows/gradle-release.yml@main
    with:
      project_name: "Project" # TODO: replace with actual project name
      # java_version: "21"
      # gradle_extra_args: ""
      # release_maven_central: false
      # release_files: ""
    secrets:
      # HYPERA_SIGNING_KEY: "${{ secrets.HYPERA_SIGNING_KEY }}"
      # HYPERA_SIGNING_PASSWORD: "${{ secrets.HYPERA_SIGNING_PASSWORD }}"
      # HYPERA_RELEASES_USERNAME: "${{ secrets.HYPERA_RELEASES_USERNAME }}"
      # HYPERA_RELEASES_PASSWORD: "${{ secrets.HYPERA_RELEASES_PASSWORD }}"
      # SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
      # SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
      GITHUB_RELEASE_TOKEN: "${{ secrets.GITHUB_RELEASE_TOKEN }}"
