#
# This file is a part of HyperaDev/actions, licensed under the MIT License.
#
# Copyright (c) 2021-2024 Joshua Sing <joshua@hypera.dev>
# Copyright (c) 2021-2023 LooFifteen <luis@lu15.dev>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# GitHub Actions workflow to publish unstable snapshots.
name: "Snapshot"
on:
  workflow_call:
    inputs:
      java_version:
        description: "JDK version to be used when building"
        default: "21" # Use latest JDK LTS.
        type: string
        required: false
      gradle_extra_args:
        description: "Extra arguments to execute Gradle with"
        default: ""
        type: string
        required: false
    secrets:
      HYPERA_SIGNING_KEY:
        description: "Hypera Development GPG signing key"
        required: false
      HYPERA_SIGNING_PASSWORD:
        description: "Hypera Development GPG signing key password"
        required: false
      HYPERA_SNAPSHOTS_USERNAME:
        description: "Hypera Development snapshots repository username"
        required: false
      HYPERA_SNAPSHOTS_PASSWORD:
        description: "Hypera Development snapshots repository password"
        required: false
      SONATYPE_USERNAME:
        description: "Sonatype OSSRH username"
        required: false
      SONATYPE_PASSWORD:
        description: "Sonatype OSSRH password"
        required: false

permissions:
  contents: read

jobs:
  publish:
    name: "Publish"
    runs-on: "ubuntu-latest"
    environment:
      name: "snapshot"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: true

      - name: "Validate Gradle wrapper"
        uses: gradle/actions/wrapper-validation@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

      - name: "Setup JDK ${{ inputs.java_version }}"
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          java-version: "${{ inputs.java_version }}"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          gradle-version: "wrapper"

      - name: "Validate version"
        run: |
          VERSION="$(./gradlew properties | awk '/^version:/ { print $2; }')"
          if ! echo "$VERSION" | grep -q 'SNAPSHOT'; then
            echo "Release version detected, refusing to publish..."
            exit 1
          fi
          echo "Snapshot version detected"

      - name: "Publish artifacts"
        run: ./gradlew ${{ inputs.gradle_extra_args }} publish
        env:
          ORG_GRADLE_PROJECT_hyperaSigningKey: "${{ secrets.HYPERA_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_hyperaSigningPassword: "${{ secrets.HYPERA_SIGNING_PASSWORD }}"
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsUsername: "${{ secrets.HYPERA_SNAPSHOTS_USERNAME }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsPassword: "${{ secrets.HYPERA_SNAPSHOTS_PASSWORD }}"

  dependency-graph:
    name: "Dependency Graph"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: true

      - name: "Setup JDK ${{ inputs.java_version }}"
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          java-version: "${{ inputs.java_version }}"
          distribution: "temurin"

      - name: "Validate Gradle wrapper"
        uses: gradle/actions/wrapper-validation@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

      - name: "Generate and submit dependency graph"
        uses: gradle/actions/dependency-submission@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
